services:
  # Service for the development environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
    volumes:
      - .:/app
    profiles:
      - dev

  pr:
  # Service for the production-ready environment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PROFILE=pr
    profiles:
      - pr
